# Generated by Django 3.0.6 on 2020-12-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=10)),
                ('datestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(max_length=10)),
                ('counts', models.IntegerField(default=1)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Ask')),
            ],
        ),
    ]
